### ISSUE TITLE
Images need alt text

### ISSUE THREAD

**Issue by cehfisher** [lauriii/umami#142] opened 2018-01-06 23:02 UTC
I assume there is no alt text for the current images because they are just placeholders, but opening this ticket as a reminder to update this when the real images are in place.

**Comment by DuaelFr** [comment] 2018-01-08 08:28
The problem is that there is no alt attribute at all. Even decorative images should at least have an empty alt attribute. :)

**Comment by markconroy** [comment] 2018-01-11 20:14
The two image fields currently on content types both have alt field enabled and set as required. So, I presume this will be fixed before 8.5.x
![screen shot 2018-01-11 at 20 13 14](https://user-images.githubusercontent.com/2183332/34845222-10193032-f70c-11e7-9247-7944e40a22ba.png)

**Comment by fuzzbomb** [comment] 2018-01-11 21:56
The custom banner block type doesn't have the imagefield alt text enabled.  Found that during Tuesday's review.

**Comment by fuzzbomb** [comment] 2018-01-11 21:57
Is Umami theme the right place for this issue? Field config and CSV content is the profile repo....

**Comment by markconroy** [comment] 2018-01-12 16:11
I came here to say the same thing! I'll close this one.

**Closed as completed by markconroy** 2018-01-12 16:11 UTC
